In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
irisdata = pd.read_csv("dataset2.csv")
irisdata.head()


A      B      C      D Class
0  0.982  2.343  1.209  4.567     X
1  1.234  0.567  3.456  2.345     Z
2  0.567  2.345  1.234  4.567     Y
3  2.345  0.982  4.567  1.209     X
4  1.209  3.456  0.567  2.343     Y

In [4]:
X = irisdata.drop('Class', axis=1)
y = irisdata['Class']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)
from sklearn.svm import SVC
svclassifier = SVC(kernel='rbf')
svclassifier.fit(X_train, y_train)
y_pred = svclassifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[4 0 0]
 [0 3 0]
 [0 0 2]]
              precision    recall  f1-score   support

           X       1.00      1.00      1.00         4
           Y       1.00      1.00      1.00         3
           Z       1.00      1.00      1.00         2

    accuracy                           1.00         9
   macro avg       1.00      1.00      1.00         9
weighted avg       1.00      1.00      1.00         9

