In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
irisdata = pd.read_csv("dataset2.csv")
irisdata.head()


A      B      C      D Class
0  0.982  2.343  1.209  4.567     X
1  1.234  0.567  3.456  2.345     Z
2  0.567  2.345  1.234  4.567     Y
3  2.345  0.982  4.567  1.209     X
4  1.209  3.456  0.567  2.343     Y

In [2]:
X = irisdata.drop('Class', axis=1)
y = irisdata['Class']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)
from sklearn.svm import SVC
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(X_train, y_train)
y_pred = svclassifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[1 0 0]
 [5 0 0]
 [3 0 0]]
              precision    recall  f1-score   support

           X       0.11      1.00      0.20         1
           Y       0.00      0.00      0.00         5
           Z       0.00      0.00      0.00         3

    accuracy                           0.11         9
   macro avg       0.04      0.33      0.07         9
weighted avg       0.01      0.11      0.02         9



C:\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
